wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.3
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701998104.289238
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.8.3
      5: 0.16.0
      8:
      - 5
      - 13
      13: darwin-x86_64
dataset:
  desc: null
  value: cifar100
root:
  desc: null
  value: ../dataset/
arch:
  desc: null
  value: resnet32
num_classes:
  desc: null
  value: 100
imbanlance_rate:
  desc: null
  value: 0.01
lr:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 64
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.005
resample_weighting:
  desc: null
  value: 0.0
label_weighting:
  desc: null
  value: 1.0
contrast_weight:
  desc: null
  value: 10
beta:
  desc: null
  value: 0.5
loss:
  desc: null
  value: ce
eps:
  desc: null
  value: 0.05
etf_cls:
  desc: null
  value: true
mixup:
  desc: null
  value: 0
mixup_alpha:
  desc: null
  value: 1.0
seed:
  desc: null
  value: 3407
print_freq:
  desc: null
  value: 1000
gpu:
  desc: null
  value: null
workers:
  desc: null
  value: 4
resume:
  desc: null
  value: null
start_epoch:
  desc: null
  value: 0
root_model:
  desc: null
  value: ./output/
store_name:
  desc: null
  value: cifar100_resnet32/0.01/name_2023-12-08
debug:
  desc: null
  value: 10
knn:
  desc: null
  value: false
